### ISSUE TITLE
Crash on startup on CM9 and CM10

### ISSUE THREAD

**Issue by dalb8** [Miserlou/OpenWatch---Android#12]
11-07 20:44:20.000 D/PhoneStatusBar(378): addNotification score=0
11-07 20:44:20.070 D/SizeAdaptiveLayout(378): com.android.internal.widget.SizeAdaptiveLayout@416b7c38child view android.widget.FrameLayout@4113bcb8 measured out of bounds at 95px clamped to 96px
11-07 20:44:23.570 I/ActivityManager(295): START {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/.Launcher u=0} from pid 295
11-07 20:44:23.610 D/dalvikvm(378): GC_CONCURRENT freed 1612K, 41% free 9554K/16071K, paused 5ms+17ms, total 86ms
11-07 20:44:23.690 W/IInputConnectionWrapper(31734): showStatusIcon on inactive InputConnection
11-07 20:44:23.810 I/AbstractArt(445): Loading battle group 105
11-07 20:44:23.810 D/BattleBackground(445): background group index: 105
11-07 20:44:23.820 D/BattleBackground(445): loaded layers: 280, 0
11-07 20:44:23.820 I/Enemy   (445): Mostly Bad Fly palette number: 2
11-07 20:44:23.820 I/Enemy   (445): Loading existing sprite: Mostly Bad Fly.png
11-07 20:44:23.850 I/Renderer(445): Surface created
11-07 20:44:23.860 D/FPS     (445): FPS: 7.6910214
11-07 20:44:23.860 D/RenderTime(445): Time to render frame: 4.25ms
11-07 20:44:24.630 I/ActivityManager(295): START {act=android.intent.action.SEARCH_LONG_PRESS flg=0x10000000 cmp=vu.de.urpool.quickdroid/.Quickdroid u=0} from pid 25233
11-07 20:44:24.760 V/PhoneStatusBar(378): setLightsOn(true)
11-07 20:44:24.790 D/PhoneStatusBar(378): addNotification score=0
11-07 20:44:24.890 D/SizeAdaptiveLayout(378): com.android.internal.widget.SizeAdaptiveLayout@4128acf8child view android.widget.FrameLayout@41295700 measured out of bounds at 95px clamped to 96px
11-07 20:44:24.930 D/dalvikvm(295): GC_CONCURRENT freed 2697K, 42% free 22513K/38535K, paused 23ms+20ms, total 233ms
11-07 20:44:24.960 D/SizeAdaptiveLayout(378): com.android.internal.widget.SizeAdaptiveLayout@4128acf8child view android.widget.FrameLayout@41295700 measured out of bounds at 95px clamped to 96px
11-07 20:44:26.580 D/dalvikvm(31677): GC_CONCURRENT freed 2357K, 43% free 4851K/8451K, paused 23ms+5ms, total 87ms
11-07 20:44:26.580 D/dalvikvm(31677): WAIT_FOR_CONCURRENT_GC blocked 16ms
11-07 20:44:26.730 D/dalvikvm(295): GC_EXPLICIT freed 2237K, 48% free 20314K/38535K, paused 6ms+11ms, total 143ms
11-07 20:44:29.640 I/ActivityManager(295): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ale.openwatch/.MainActivityGroup u=0} from pid 31677
11-07 20:44:29.740 I/ActivityManager(295): Start proc org.ale.openwatch for activity org.ale.openwatch/.MainActivityGroup: pid=31812 uid=10152 gids={1006, 1015, 3003, 1028}
11-07 20:44:29.760 I/dalvikvm(31812): Turning on JNI app bug workarounds for target SDK version 4...
11-07 20:44:29.780 E/Trace   (31812): error opening trace file: No such file or directory (2)
11-07 20:44:30.030 D/AndroidRuntime(31812): Shutting down VM
11-07 20:44:30.030 W/dalvikvm(31812): threadid=1: thread exiting with uncaught exception (group=0x40d8a300)
11-07 20:44:30.060 E/AndroidRuntime(31812): FATAL EXCEPTION: main
11-07 20:44:30.060 E/AndroidRuntime(31812): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ale.openwatch/org.ale.openwatch.MainActivityGroup}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2185)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2210)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread.access$600(ActivityThread.java:142)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.os.Handler.dispatchMessage(Handler.java:99)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.os.Looper.loop(Looper.java:137)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread.main(ActivityThread.java:4931)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at dalvik.system.NativeStart.main(Native Method)
11-07 20:44:30.060 E/AndroidRuntime(31812): Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
11-07 20:44:30.060 E/AndroidRuntime(31812):     at org.ale.openwatch.MainActivityGroup.onCreate(MainActivityGroup.java:320)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.Activity.performCreate(Activity.java:5008)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
11-07 20:44:30.060 E/AndroidRuntime(31812):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2139)
11-07 20:44:30.060 E/AndroidRuntime(31812):     ... 11 more
11-07 20:44:30.100 W/ActivityManager(295):   Force finishing activity org.ale.openwatch/.MainActivityGroup
11-07 20:44:30.130 W/ActivityManager(295):   Force finishing activity vu.de.urpool.quickdroid/.Quickdroid
11-07 20:44:30.630 W/ActivityManager(295): Activity pause timeout for ActivityRecord{41116e78 org.ale.openwatch/.MainActivityGroup}
11-07 20:44:30.730 I/ActivityManager(295): No longer want android.process.acore (pid 31714): hidden #6
11-07 20:44:30.780 I/AbstractArt(445): Loading battle group 208
11-07 20:44:30.780 D/BattleBackground(445): background group index: 208
11-07 20:44:30.780 D/BattleBackground(445): loaded layers: 201, 200
11-07 20:44:30.780 I/Enemy   (445): Kraken palette number: 1
11-07 20:44:30.780 I/Enemy   (445): Loading existing sprite: Kraken.png
11-07 20:44:30.800 I/Renderer(445): Surface created
11-07 20:44:30.810 D/FPS     (445): FPS: 10.797582
11-07 20:44:30.810 D/RenderTime(445): Time to render frame: 5.3733335ms
11-07 20:44:32.090 I/Process (31812): Sending signal. PID: 31812 SIG: 9
11-07 20:44:32.110 I/ActivityManager(295): Process org.ale.openwatch (pid 31812) has died.
11-07 20:44:32.120 W/IInputConnectionWrapper(31677): showStatusIcon on inactive InputConnection
11-07 20:44:32.830 D/FPS     (445): FPS: 47.61905
11-07 20:44:32.830 D/RenderTime(445): Time to render frame: 4.0625ms
11-07 20:44:33.740 D/dalvikvm(378): GC_FOR_ALLOC freed 1851K, 39% free 9958K/16071K, paused 36ms, total 36ms
11-07 20:44:34.100 D/dalvikvm(378): GC_CONCURRENT freed 181K, 24% free 12286K/16071K, paused 7ms+9ms, total 76ms
11-07 20:44:34.860 D/FPS     (445): FPS: 53.20736
11-07 20:44:34.860 D/RenderTime(445): Time to render frame: 2.7850468ms
11-07 20:44:36.440 I/ActivityManager(295): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10304000 cmp=org.ale.openwatch/.MainActivityGroup u=0} from pid 378
11-07 20:44:36.550 I/ActivityManager(295): Start proc org.ale.openwatch for activity org.ale.openwatch/.MainActivityGroup: pid=31829 uid=10152 gids={1006, 1015, 3003, 1028}
11-07 20:44:36.560 I/dalvikvm(31829): Turning on JNI app bug workarounds for target SDK version 4...
11-07 20:44:36.580 E/Trace   (31829): error opening trace file: No such file or directory (2)
11-07 20:44:36.710 D/AndroidRuntime(31829): Shutting down VM
11-07 20:44:36.710 W/dalvikvm(31829): threadid=1: thread exiting with uncaught exception (group=0x40d8a300)
11-07 20:44:36.710 E/AndroidRuntime(31829): FATAL EXCEPTION: main
11-07 20:44:36.710 E/AndroidRuntime(31829): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ale.openwatch/org.ale.openwatch.MainActivityGroup}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2185)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2210)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread.access$600(ActivityThread.java:142)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.os.Handler.dispatchMessage(Handler.java:99)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.os.Looper.loop(Looper.java:137)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread.main(ActivityThread.java:4931)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at dalvik.system.NativeStart.main(Native Method)
11-07 20:44:36.710 E/AndroidRuntime(31829): Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
11-07 20:44:36.710 E/AndroidRuntime(31829):     at org.ale.openwatch.MainActivityGroup.onCreate(MainActivityGroup.java:320)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.Activity.performCreate(Activity.java:5008)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
11-07 20:44:36.710 E/AndroidRuntime(31829):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2139)
11-07 20:44:36.710 E/AndroidRuntime(31829):     ... 11 more
11-07 20:44:36.710 W/ActivityManager(295):   Force finishing activity org.ale.openwatch/.MainActivityGroup
11-07 20:44:37.290 W/ActivityManager(295): Activity pause timeout for ActivityRecord{41161438 org.ale.openwatch/.MainActivityGroup}
11-07 20:44:37.440 I/AbstractArt(445): Loading battle group 197
11-07 20:44:37.440 D/BattleBackground(445): background group index: 197
11-07 20:44:37.440 D/BattleBackground(445): loaded layers: 194, 193
11-07 20:44:37.440 I/Enemy   (445): Master Belch palette number: 6
11-07 20:44:37.440 I/Enemy   (445): Loading existing sprite: Master Belch.png
11-07 20:44:37.460 I/Renderer(445): Surface created
11-07 20:44:37.460 D/FPS     (445): FPS: 42.101196
11-07 20:44:37.460 D/RenderTime(445): Time to render frame: 3.357798ms
11-07 20:44:38.730 I/Process (31829): Sending signal. PID: 31829 SIG: 9
11-07 20:44:38.760 I/ActivityManager(295): Process org.ale.openwatch (pid 31829) has died.
11-07 20:44:38.760 W/InputMethodManagerService(295): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@417cf640 attribute=null
11-07 20:44:39.480 D/FPS     (445): FPS: 48.40319
11-07 20:44:39.480 D/RenderTime(445): Time to render frame: 4.2371135ms
11-07 20:44:40.210 D/dalvikvm(378): GC_FOR_ALLOC freed 4584K, 45% free 9413K/16839K, paused 37ms, total 37ms
11-07 20:44:40.360 D/dalvikvm(378): GC_CONCURRENT freed 137K, 32% free 11594K/16839K, paused 2ms+4ms, total 40ms
11-07 20:44:40.360 D/dalvikvm(378): WAIT_FOR_CONCURRENT_GC blocked 25ms
11-07 20:44:40.730 W/ActivityManager(295): Activity destroy timeout for ActivityRecord{41116e78 org.ale.openwatch/.MainActivityGroup}
11-07 20:44:41.510 D/FPS     (445): FPS: 55.63835
11-07 20:44:41.510 D/RenderTime(445): Time to render frame: 2.4642856ms
11-07 20:44:42.900 V/PhoneStatusBar(378): setLightsOn(true)
11-07 20:44:47.409 W/ActivityManager(295): Activity destroy timeout for ActivityRecord{41161438 org.ale.openwatch/.MainActivityGroup}
11-07 20:44:50.930 D/dalvikvm(31734): GC_CONCURRENT freed 3294K, 49% free 5081K/9799K, paused 6ms+4ms, total 55ms
11-07 20:44:50.940 D/dalvikvm(31734): WAIT_FOR_CONCURRENT_GC blocked 24ms
11-07 20:44:50.970 D/dalvikvm(31734): GC_FOR_ALLOC freed 299K, 49% free 5055K/9799K, paused 18ms, total 18ms
11-07 20:44:51.020 D/dalvikvm(31734): GC_FOR_ALLOC freed 241K, 50% free 4995K/9799K, paused 17ms, total 17ms
11-07 20:44:51.020 I/dalvikvm-heap(31734): Grow heap (frag case) to 13.470MB for 279056-byte allocation
11-07 20:44:52.750 W/ThrottleService(295): unable to find stats for iface vsnet0
11-07 20:44:56.350 I/Choreographer(31734): Skipped 54 frames!  The application may be doing too much work on its main thread.
11-07 20:44:56.460 D/dalvikvm(31734): GC_CONCURRENT freed 1145K, 48% free 5597K/10567K, paused 2ms+4ms, total 26ms
11-07 20:44:56.700 D/dalvikvm(31734): GC_FOR_ALLOC freed 836K, 46% free 5731K/10567K, paused 27ms, total 27ms

**Comment by dalb8** [comment]
I should mention that this was built without the market library referenced in project.properties

**Comment by imz** [comment]
Yes, openwatch from f-droid crashes on my cm-10.1 on startup. I have installed the latest version from f-droid as of today.

**Comment by imz** [comment]
I use a Samsung Galaxy S.

**Comment by haxwithaxe** [comment]
Same issue on galaxy 3 (sgh-t999l) cm10.2
